import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Header } from '../ui/header/header';
import { archivoNarrow, geistSans, geistMono } from '@/lib/fonts';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${archivoNarrow.variable} antialiased`}>
				<Header />
				<main className='site-grid font-sans overflow-hidden'>
					<div className='site-gutter-left bg-hatch'></div>
					<div className='site-content'>{children}</div>
					<div className='site-gutter-right bg-hatch'></div>
				</main>
			</body>
		</html>
	);
}
