import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Header } from '../ui/header/header';
import { archivoNarrow, geistSans, geistMono } from '@/lib/fonts';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${archivoNarrow.variable} antialiased`}>
				<Header />
				<div className='flex min-h-screen items-top justify-center bg-zinc-50 font-sans dark:bg-black'>
					<main className='flex w-full flex-col items-center justify-between px-6 bg-white dark:bg-black overflow-hidden'>
						{children}
					</main>
				</div>
			</body>
		</html>
	);
}
